#defines when to trigger this workflow, in this case on push's and merged PR's
on: push

#defines the jobs to be run
jobs:

  #only 1 job run snyk delta and if that passes run snyk monitor 
  snyk-delta-monitor:

    #run this on an ubuntu runner using one of snyks node images as a container
    runs-on: ubuntu-latest
    container: docker://snyk/snyk:node

    #this is where you define the steps to be run within each job
    steps:
     #use the current repo
     - uses: actions/checkout@master
     #install snyk-delta/html
     - run: npm i -g snyk-delta
     - run: npm i -g snyk-to-html
     #authenticate with your snyk token
     - run: snyk auth 4b876be1-edc2-4d04-be53-7c91508920c6
     #run a snyk test only failing of there are new critical issues, Not if the project hasn't been monitored
     - run: snyk test --unmanaged --severity-threshold=critical --json | snyk-to-html -o results.html
     #if the previous scan doesn't come back with an error code then monitor the project
     - run: snyk monitor
